# Generated by Django 4.0.3 on 2022-04-06 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_post', '0005_comment_delete_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.RemoveField(
            model_name='comment',
            name='container_post',
        ),
        migrations.AddField(
            model_name='comment',
            name='container_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home_post.thought'),
        ),
    ]
