# Generated by Django 4.0.3 on 2022-04-07 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_post', '0006_alter_comment_comment_remove_comment_container_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='container_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='home_post.thought'),
        ),
    ]
