# Generated by Django 4.0.3 on 2022-04-07 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_message', models.CharField(blank=True, max_length=500)),
                ('message_ricevere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='msg_r', to=settings.AUTH_USER_MODEL)),
                ('message_sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='msg_s', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
